fix: fix admin and user login
mvn-internship/summer-2021-olympic pull request #25
Opened 2021-10-07 14:19 UTC by mvn-thuongmai-dn

## Fix user login
- admin side login
- user side login

2021-10-10 15:12 UTC, mvn-quangtran-dn commented on app/Http/Controllers/Auth/LoginController.php
> +        return back()->with(['error' => 'Login failed!']);
tránh hard code :
tất cả text,messege define trong resources/lang/en/message.php
các số define thành constant trong model, hoặc trong config/constants.php

2021-10-10 15:13 UTC, mvn-quangtran-dn commented on app/Http/Controllers/Auth/LoginController.php
> +        ]);
chuyển cục validation sang dùng class form request

2021-10-10 15:22 UTC, mvn-quangtran-dn commented on config/constants.php
> +}
config/constants.php ko viết kiểu này em mà sẽ return kiểu array
return [
  'role' => [
      'admin_site' => [
     'admin',
     'staff',
     'secretary'
],
'user_site' => [
    'participant',
    'team_manager'
  ]
]

];

Còn  class AuthUtils thì tạo ra trong app\Helpers\AuthUtils.php 
tham khảo  : https://viblo.asia/p/custom-helper-laravel-eW65GbLLlDO

2021-10-10 15:25 UTC, mvn-quangtran-dn commented on resources/views/admin/layouts/master.blade.php
>                  <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
text define trong resources/lang/en/label.php
sửa  cho tất cả các file còn lại. tránh hard code ntn

2021-10-10 15:26 UTC, mvn-thuongmai-dn commented on resources/views/admin/layouts/master.blade.php
>                  <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
dạ anh

2021-10-10 15:27 UTC, mvn-thuongmai-dn commented on config/constants.php
> +}
chữ dùng bên lang
số là dùng bên config/constants đúng hông a

2021-10-10 15:28 UTC, mvn-quangtran-dn commented on app/Http/Middleware/CheckAdminSideRole.php
> +                if (in_array($role->name, StaticArray::$admin_side)) {
sửa bên constants xong sửa chỗ này luôn

2021-10-10 15:28 UTC, mvn-quangtran-dn requested changes
check comt

2021-10-12 04:53 UTC, mvn-quangtran-dn approved these changes
LGTM

2021-10-12 04:53 UTC, merged